-- create_schema.sql
-- Minimal DDL for PL/SQL ETL example (staging, dimensions, fact, sequences)

CREATE TABLE staging_water (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  sensor_id VARCHAR2(50),
  sensor_type VARCHAR2(50),
  measure_date DATE,
  measure_value NUMBER,
  location VARCHAR2(200),
  recorded_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT pk_staging PRIMARY KEY (id)
);

CREATE TABLE dim_sensor (
  sensor_key NUMBER PRIMARY KEY,
  sensor_id VARCHAR2(50) UNIQUE,
  sensor_type VARCHAR2(50)
);

CREATE SEQUENCE seq_dim_sensor START WITH 1 INCREMENT BY 1;

CREATE TABLE dim_location (
  location_key NUMBER PRIMARY KEY,
  location_name VARCHAR2(200) UNIQUE
);

CREATE SEQUENCE seq_dim_location START WITH 1 INCREMENT BY 1;

CREATE TABLE fact_measurements (
  fact_key NUMBER PRIMARY KEY,
  sensor_key NUMBER,
  location_key NUMBER,
  measure_date DATE,
  measure_value NUMBER,
  load_ts TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE SEQUENCE seq_fact_measurements START WITH 1 INCREMENT BY 1;

COMMIT;
